on: [push]

jobs:
  helmsman_test_job:
    runs-on: ubuntu-latest
    name: A job to apply helmsman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helmsman Test Step
        id: helmsman
        uses: ./
        with:
          args: '-f hello'
